<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mv</string>
	</array>
	<key>firstLineMatch</key>
	<string>^&lt;MIVA </string>
	<key>name</key>
	<string>Miva Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in Miva functions</string>
			<key>match</key>
			<string>(?i)\b(is(a(l(num|pha)|scii)|cntrl|(x?)digit|graph|(low|upp)er|p(rint|unct)|space)|glosub(_array)?|pad(l|r)|gettoken|makesessionid|mktime_t|(de|en)codeattribute|int|to(upp|low)er|substring(_var)?|len(_var)?|power|ascii(char|value)|(de|en)codeentities|indexof(i)?|file_(append|create|read(_bytes)?)|gd(Clear|Image|Last|True).+?|fsize|xml_parse_(.*?)|crypto_(.*?)|miva_member_exists|miva_array_(binarysearch|c(lear|ollapse|opy(_ref)?)|de(lete|serialize)|elements|find|insert(_(ref|var))?|m(ax|erge(_ref)?|in)|next|p(op(_ref)?|revious)|s(e(arch|rialize)|hift(_ref)?|ort))|miva_variable_value|miva_struct_members|time(zone|_t_(dayof(month|week|year)|hour|m(in|onth)|sec|year))|rsa_(.*?)|(f|s)(copy|delete|exists)|bf_(de|en)crypt|(f|s)isdir|(l|r)?trim)\b(?=\()</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;MvCOMMENT&gt;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Match any MvCOMMENT blocks</string>
			<key>end</key>
			<string>&lt;/MvCOMMENT&gt;</string>
			<key>name</key>
			<string>comment.block.mivascript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(&lt;MvFUNCTION)\s+(?:(NAME)\s*=\s*"(\w+)")(?:\s*(PARAMETERS)\s*=\s*"(.*?)")?(?:\s*(STANDARDOUTPUTLEVEL)\s*=\s*(".*?"))?(?:\s*(ERROROUTPUTLEVEL)\s*=\s*(".*?"))?|(&lt;/MvFUNCTION)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>mivascript.function.mivascript</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>mivascript.function.mivascript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mivascript</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.mivascript</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.mivascript</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Match the MvFUNCTION</string>
			<key>end</key>
			<string>&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>mivascript.function.mivascript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>The keyword at the top of most MV files</string>
			<key>match</key>
			<string>^&lt;MIVA\s</string>
			<key>name</key>
			<string>keyword.control.mivascript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.localname.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Attributes e.g. PARAMETERS ERROROUTPUTLEVEL INDEX etc..</string>
			<key>match</key>
			<string>\b([A-Z-]+\b)\s*=</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comparison Operators</string>
			<key>match</key>
			<string>\b(EQ|GT|LT|NE|GE|LE)\b</string>
			<key>name</key>
			<string>keyword.operator.comparison.mivascript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Logical Operators</string>
			<key>match</key>
			<string>\b(NOT|AND|OR|ISNULL)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.mivascript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Bitwise Operators</string>
			<key>match</key>
			<string>\b(BIT(AND|OR|XOR|OC|SL|SR))\b</string>
			<key>name</key>
			<string>keyword.operator.bitwise.mivascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$</string>
			<key>name</key>
			<string>keyword.operator.string.mivascript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;Mv[A-Z]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Mathces opening Mv* tags</string>
			<key>end</key>
			<string>&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mivascript</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Matches closing Mv* tags</string>
			<key>match</key>
			<string>&lt;/Mv[A-Z]+&gt;</string>
			<key>name</key>
			<string>keyword.control.mivascript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([A-Za-z0-9_]+)(?=\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.file.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Functions Calls</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[.*?\])\.([A-Za-z0-9_]+)(?=\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>mivascript.mvdo.mivascript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.file.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>MvDOs</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Single Quoted Strings</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mivascript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.mivascript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.mivascript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"\w+</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Double Quoted Strings</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mivascript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.mivascript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.mivascript</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mivascript</string>
	<key>uuid</key>
	<string>1a3a4d44-98f3-4d0f-a124-520edd1d96c9</string>
</dict>
</plist>
