<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mv</string>
	</array>
	<key>firstLineMatch</key>
	<string>^&lt;MIVA </string>
	<key>name</key>
	<string>Miva Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in Miva functions</string>
			<key>match</key>
			<string>(?&lt;=\s)(is(a(l(num|pha)|scii)|cntrl|(x?)digit|graph|(low|upp)er|p(rint|unct)|space)|glosub(_array)?|pad(l|r)|gettoken|makesessionid|mktime_t|(de|en)codeattribute|int|to(upp|low)er|substring(_var)?|len(_var)?|power|ascii(char|value)|(de|en)codeentities|indexof(i)?|file_(append|create|read(_bytes)?)|gd(Clear|Image|Last|True).+?|fsize|xml_parse_(.*?)|crypto_(.*?)|miva_array_(binarysearch|c(lear|ollapse|opy(_ref)?)|de(lete|serialize)|elements|find|insert(_(ref|var))?|m(ax|erge(_ref)?|in)|next|p(op(_ref)?|revious)|s(e(arch|rialize)|hift(_ref)?|ort))|miva_variable_value|time(zone|_t_(dayof(month|week|year)|hour|m(in|onth)|sec|year))|rsa_(.*?)|(f|s)(copy|delete|exists)|bf_(de|en)crypt|(f|s)isdir|(l|r)?trim)\(</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>errorcodes.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Error codes</string>
			<key>match</key>
			<string>'([A-Z]+-[A-Z]+-[A-Z]+-[0-9]{5}|#Error#)'</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;MvCOMMENT&gt;</string>
			<key>comment</key>
			<string>Any opening/closing Miva tag</string>
			<key>end</key>
			<string>&lt;/MvCOMMENT&gt;</string>
			<key>name</key>
			<string>comment.mivascript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment.mivascript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Any opening/closing Miva tag</string>
			<key>match</key>
			<string>&lt;MvFUNCTION |&lt;/MvFUNCTION&gt;</string>
			<key>name</key>
			<string>mivascript.function.mivascript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Any opening/closing Miva tag</string>
			<key>match</key>
			<string>&lt;Mv([^\s]+)|&lt;/Mv([^&gt;]+)&gt;|^&lt;MIVA</string>
			<key>name</key>
			<string>keyword.control.mivascript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.localname.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Attributes e.g. PARAMETERS ERROROUTPUTLEVEL INDEX etc..</string>
			<key>match</key>
			<string>\s*([A-Z-]+)\s+=</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.file.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matches function names</string>
			<key>match</key>
			<string>([A-Za-z0-9_]+)\(</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s(EQ|GT|LT|NE|GE|LE)\s</string>
			<key>name</key>
			<string>keyword.operator.comparison.mivascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s(NOT|AND|OR|ISNULL)\s</string>
			<key>name</key>
			<string>keyword.operator.logical.mivascript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s(BIT(AND|OR|XOR|OC|SL|SR))\s</string>
			<key>name</key>
			<string>keyword.operator.bitwise.mivascript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>mivascript.mvdo.mivascript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Inline MvDOs</string>
			<key>match</key>
			<string> (\[ g\.[^\]]+ \])\.</string>
			<key>name</key>
			<string></string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mivascript</string>
	<key>uuid</key>
	<string>1a3a4d44-98f3-4d0f-a124-520edd1d96c9</string>
</dict>
</plist>
